import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://webtcdgvzmdcmheghklu.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYnRjZGd2em1kY21oZWdoa2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzEyNDAsImV4cCI6MjA1NDI0NzI0MH0.zrnAS-BURa0DWEjGwzAfDitdAVEA23Jzreozb4pjhu8';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export type HeatPumpRequest = {
  id: string;
  created_at: string;
  first_name: string;
  last_name: string;
  postal_code: string;
  birth_date?: string;
  internal_id?: string;
  street?: string;
  house_number?: string;
  city?: string;
  property_postal_code?: string;
  construction_year?: string;
  living_area?: string;
  roof_insulated?: boolean;
  windows_insulated?: boolean;
  facade_insulated?: boolean;
  heating_load?: string;
  fuel_consumption?: string;
  heating_location?: string;
  heating_install_year?: string;
  boiler_type?: string;
  heating_power?: string;
  fuel_type?: string;
  additional_heat_source?: boolean;
  additional_heat_source_type?: string;
  additional_heat_source_support?: string;
  heating_circuits?: string;
  heating_type?: string;
  household_persons?: string;
  water_heating_type?: string;
  water_tank_size?: string;
  water_comfort?: string;
  distance_to_heating_room?: string;
  installation_type?: string;
  ground_material?: string;
  distance_to_building?: string;
  narrowest_passage?: string;
  heating_room_height?: string;
  tariff_module?: string;
  is_owner?: boolean;
  building_permit_date?: string;
  fundable_units?: string;
  fundable_area?: string;
  additional_costs?: string;
  additional_info?: string;
  contact_email?: string;
  contact_phone?: string;
  preferred_contact?: string;
  appointment_type?: string;
  status?: string;
};
