// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://webtcdgvzmdcmheghklu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYnRjZGd2em1kY21oZWdoa2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzEyNDAsImV4cCI6MjA1NDI0NzI0MH0.zrnAS-BURa0DWEjGwzAfDitdAVEA23Jzreozb4pjhu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);